; Mason Fabel
; 7 April 14
; CS 150
; Homework 5
;
	.ORIG x3000
; ----- Initialization
INIT	LEA R0, MSG_INIT
	PUTS
; ----- Main loop
MAIN	IN
	LD R1, VAL_OFF
	ADD R2, R0, R1
	LDR R0, R2, x0000
	JSRR R0
	BRnzp MAIN
; ----- Operator 'A'
OPER_CAPA	ST R7, VAR_R7
	IN
	ST R0, VAR_A
	LD R7, VAR_R7
	RET
; ----- Operator 'a'
OPER_LOWA	ST R7, VAR_R7
	LD R0, VAR_A
	JSR PRINT_REV
	LD R7, VAR_R7
	RET
; ----- Operator 'y'
; ----- Operator 'B'
OPER_CAPB	ST R7, VAR_R7
	IN
	ST R0, VAR_B
	LD R7, VAR_R7
	RET
; ----- Operator 'b'
OPER_LOWB	ST R7, VAR_R7
	LD R0, VAR_B
	JSR PRINT_REV
	LD R7, VAR_R7
	RET
; ----- Operator 'z'
; ----- Operator '='
OPER_EQ	ST R7, VAR_R7
	LD R0, VAR_A
	LD R1, VAR_B
	ST R1, VAR_A
	ST R0, VAR_B
	LD R7, VAR_R7
	RET
; ----- Operator '+'
OPER_PLUS	ST R7, VAR_R7
	LD R7, VAR_R7
	RET
; ----- Operator '~'
OPER_TILDA	ST R7, VAR_R7
	LD R7, VAR_R7
	RET
; ----- Operator '^'
OPER_HAT	ST R7, VAR_R7
	LD R7, VAR_R7
	RET
; ----- Operator 'X'
OPER_CAPX	LEA R0, MSG_EXIT
	PUTS
	HALT
; ----- Invalid operation
OPER_NO	ST R7, VAR_R7
	LEA R0, MSG_UNKN
	PUTS
	LD R7, VAR_R7
	RET
; ----- Print R0 backwards
PRINT_REV	ST R7, PR_R7
	AND R1, R0, R0
	AND R2, R2, x0000
	ADD R2, R2, x0001
PR_1	AND R3, R1, R2
	BRz PR_2
	LD R0, CHAR_1
	OUT
	BRnzp PR_3
PR_2	LD R0, CHAR_0
	OUT
PR_3	ADD R2, R2, R2
	BRnp PR_1
	LD R0, CHAR_CR
	OUT
	LD R7, PR_R7
	RET
PR_R7	.BLKW 1
; ----- Constants
VAL_OFF	.FILL TABLE
; ----- Strings
CHAR_CR	.FILL x000D
CHAR_0	.FILL x0030
CHAR_1	.FILL x0031
MSG_INIT	.STRINGZ "__WELCOME__"
MSG_UNKN	.STRINGZ "?"
MSG_EXIT	.STRINGZ "finished."
; ----- Variables
VAR_A	.FILL xAAAA
VAR_B	.FILL xBBBB
VAR_R7	.BLKW 1
; ----- ASCII Vector Table
TABLE	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_EQ
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_CAPA
	.FILL OPER_CAPB
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_CAPX
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_LOWA
	.FILL OPER_LOWB
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.FILL OPER_NO
	.END
